export type ExamSeed = {
  slug: string;
  name: string;
  fullName: string;
  conductedBy: string;
  force: string;
  eligibility: string;
  pattern: string;
  description: string;
  icon: string;
  color: string;
  frequency: string;
  papers: { title: string; subject: string; durationMinutes: number; marksPerQuestion: number; negativeMarks: number; subjects: string[]; count: number }[];
};

export const examSeeds: ExamSeed[] = [
  {
    slug: "nda",
    name: "NDA & NA",
    fullName: "National Defence Academy & Naval Academy Examination",
    conductedBy: "UPSC",
    force: "Tri-Service",
    eligibility: "12th pass (PCM for Air Force/Navy), age 16.5–19.5 years, unmarried",
    pattern: "Paper I Mathematics (300 marks, 120 Qs, 2.5 hrs) + Paper II GAT (600 marks, 150 Qs, 2.5 hrs) followed by SSB Interview (900 marks)",
    description: "The gateway to join the Army, Navy and Air Force right after class 12. One of the most prestigious exams for young aspirants.",
    icon: "🎖️",
    color: "from-amber-500 to-orange-600",
    frequency: "Twice a year (April & September)",
    papers: [
      { title: "NDA Mathematics Mock Test 1", subject: "Mathematics", durationMinutes: 150, marksPerQuestion: 2.5, negativeMarks: 0.83, subjects: ["Mathematics"], count: 40 },
      { title: "NDA Mathematics Mock Test 2", subject: "Mathematics", durationMinutes: 150, marksPerQuestion: 2.5, negativeMarks: 0.83, subjects: ["Mathematics"], count: 40 },
      { title: "NDA GAT Mock Test 1", subject: "General Ability", durationMinutes: 150, marksPerQuestion: 4, negativeMarks: 1.33, subjects: ["English", "General Knowledge", "Science"], count: 45 },
      { title: "NDA GAT Mock Test 2", subject: "General Ability", durationMinutes: 150, marksPerQuestion: 4, negativeMarks: 1.33, subjects: ["English", "General Knowledge", "Science", "Defence"], count: 45 },
    ],
  },
  {
    slug: "cds",
    name: "CDS",
    fullName: "Combined Defence Services Examination",
    conductedBy: "UPSC",
    force: "Tri-Service",
    eligibility: "Graduate (IMA/OTA), B.E/B.Tech or Physics & Maths in graduation for AFA/INA, age 19–25 years",
    pattern: "English (100), GK (100), Elementary Mathematics (100) – 2 hrs each. OTA candidates skip Mathematics.",
    description: "For graduates aspiring to become officers through IMA, INA, AFA or OTA.",
    icon: "⚔️",
    color: "from-emerald-500 to-teal-600",
    frequency: "Twice a year (February & September)",
    papers: [
      { title: "CDS English Mock Test", subject: "English", durationMinutes: 120, marksPerQuestion: 0.83, negativeMarks: 0.28, subjects: ["English"], count: 40 },
      { title: "CDS General Knowledge Mock Test", subject: "General Knowledge", durationMinutes: 120, marksPerQuestion: 0.83, negativeMarks: 0.28, subjects: ["General Knowledge", "Science", "Defence"], count: 45 },
      { title: "CDS Elementary Mathematics Mock Test", subject: "Mathematics", durationMinutes: 120, marksPerQuestion: 1, negativeMarks: 0.33, subjects: ["Mathematics"], count: 40 },
    ],
  },
  {
    slug: "afcat",
    name: "AFCAT",
    fullName: "Air Force Common Admission Test",
    conductedBy: "Indian Air Force",
    force: "Air Force",
    eligibility: "Graduate with 60%, age 20–24 (Flying), 20–26 (Ground Duty)",
    pattern: "100 Qs, 300 marks, 2 hrs – General Awareness, Verbal Ability, Numerical Ability, Reasoning & Military Aptitude. +3 / -1 marking.",
    description: "Entry for Flying, Technical and Non-Technical branches of the Indian Air Force.",
    icon: "✈️",
    color: "from-sky-500 to-blue-700",
    frequency: "Twice a year (February & August)",
    papers: [
      { title: "AFCAT Full Length Mock 1", subject: "Full Syllabus", durationMinutes: 120, marksPerQuestion: 3, negativeMarks: 1, subjects: ["English", "General Knowledge", "Mathematics", "Reasoning"], count: 50 },
      { title: "AFCAT Full Length Mock 2", subject: "Full Syllabus", durationMinutes: 120, marksPerQuestion: 3, negativeMarks: 1, subjects: ["English", "General Knowledge", "Mathematics", "Reasoning", "Defence"], count: 50 },
      { title: "AFCAT Reasoning & Military Aptitude", subject: "Reasoning", durationMinutes: 45, marksPerQuestion: 3, negativeMarks: 1, subjects: ["Reasoning"], count: 30 },
    ],
  },
  {
    slug: "capf-ac",
    name: "CAPF (AC)",
    fullName: "Central Armed Police Forces (Assistant Commandant)",
    conductedBy: "UPSC",
    force: "CAPF",
    eligibility: "Graduate, age 20–25 years",
    pattern: "Paper I: GA & Intelligence (250 marks, 2 hrs objective). Paper II: General Studies, Essay & Comprehension (200 marks, descriptive). Then PET/PST, Medical & Interview.",
    description: "Officer entry into BSF, CRPF, CISF, ITBP and SSB.",
    icon: "🛡️",
    color: "from-rose-500 to-red-700",
    frequency: "Once a year (August)",
    papers: [
      { title: "CAPF AC Paper I Mock 1", subject: "General Ability & Intelligence", durationMinutes: 120, marksPerQuestion: 2, negativeMarks: 0.67, subjects: ["General Knowledge", "Reasoning", "Science", "Defence"], count: 50 },
      { title: "CAPF AC Paper I Mock 2", subject: "General Ability & Intelligence", durationMinutes: 120, marksPerQuestion: 2, negativeMarks: 0.67, subjects: ["General Knowledge", "Reasoning", "Mathematics", "Science"], count: 50 },
    ],
  },
  {
    slug: "agniveer-army",
    name: "Agniveer Army",
    fullName: "Indian Army Agniveer (GD / Tech / Clerk)",
    conductedBy: "Indian Army",
    force: "Army",
    eligibility: "10th/12th pass, age 17.5–21 years",
    pattern: "Online CEE: GD – 50 Qs (100 marks, 1 hr); Clerk – 50 Qs (200 marks); Tech – 50 Qs (200 marks). Negative marking 25%.",
    description: "Four-year soldier entry under the Agnipath scheme with GD, Technical, Clerk/SKT and Tradesman categories.",
    icon: "🪖",
    color: "from-lime-500 to-green-700",
    frequency: "Once a year (April)",
    papers: [
      { title: "Agniveer GD Mock Test 1", subject: "GD", durationMinutes: 60, marksPerQuestion: 2, negativeMarks: 0.5, subjects: ["General Knowledge", "Science", "Mathematics", "Reasoning"], count: 40 },
      { title: "Agniveer GD Mock Test 2", subject: "GD", durationMinutes: 60, marksPerQuestion: 2, negativeMarks: 0.5, subjects: ["General Knowledge", "Science", "Mathematics", "Reasoning"], count: 40 },
      { title: "Agniveer Clerk / SKT Mock Test", subject: "Clerk", durationMinutes: 60, marksPerQuestion: 4, negativeMarks: 1, subjects: ["General Knowledge", "English", "Mathematics", "Science"], count: 40 },
    ],
  },
  {
    slug: "agniveer-navy",
    name: "Navy Agniveer SSR/MR",
    fullName: "Indian Navy Agniveer (SSR & MR)",
    conductedBy: "Indian Navy",
    force: "Navy",
    eligibility: "SSR: 12th with Maths & Physics; MR: 10th pass. Age 17.5–21 years",
    pattern: "SSR: 100 Qs (English, Science, Maths, GK) 1 hr. MR: 50 Qs (Science & Maths, GK) 30 min. Negative 0.25.",
    description: "Sailor entry into the Indian Navy under the Agnipath scheme.",
    icon: "⚓",
    color: "from-indigo-500 to-blue-800",
    frequency: "Twice a year",
    papers: [
      { title: "Navy SSR Mock Test 1", subject: "SSR", durationMinutes: 60, marksPerQuestion: 1, negativeMarks: 0.25, subjects: ["English", "Science", "Mathematics", "General Knowledge"], count: 50 },
      { title: "Navy MR Mock Test", subject: "MR", durationMinutes: 30, marksPerQuestion: 1, negativeMarks: 0.25, subjects: ["Science", "Mathematics", "General Knowledge"], count: 30 },
    ],
  },
  {
    slug: "agniveer-vayu",
    name: "Agniveer Vayu",
    fullName: "Indian Air Force Agniveer Vayu",
    conductedBy: "Indian Air Force",
    force: "Air Force",
    eligibility: "12th with Maths, Physics & English (Science) or any stream (Other), age 17.5–21 years",
    pattern: "Science: English, Physics, Maths – 70 Qs, 60 min. Other: English, RAGA – 50 Qs, 45 min. +1 / -0.25.",
    description: "Airmen entry into the IAF under the Agnipath scheme.",
    icon: "🛩️",
    color: "from-cyan-500 to-sky-700",
    frequency: "Twice a year",
    papers: [
      { title: "Agniveer Vayu Science Mock", subject: "Science Group", durationMinutes: 60, marksPerQuestion: 1, negativeMarks: 0.25, subjects: ["English", "Science", "Mathematics"], count: 45 },
      { title: "Agniveer Vayu Other Group Mock (RAGA)", subject: "Other Group", durationMinutes: 45, marksPerQuestion: 1, negativeMarks: 0.25, subjects: ["English", "Reasoning", "General Knowledge"], count: 40 },
    ],
  },
  {
    slug: "coast-guard",
    name: "Coast Guard Navik",
    fullName: "Indian Coast Guard Navik (GD/DB) & Yantrik",
    conductedBy: "Indian Coast Guard",
    force: "Coast Guard",
    eligibility: "Navik GD: 12th with Maths & Physics; DB: 10th; Yantrik: Diploma. Age 18–22 years",
    pattern: "Stage I CGEPT: Section I (60 Qs – Maths, Science, English, Reasoning, GK) + Section II for GD. 45 min each. 0.25 negative.",
    description: "Sailor and technical entries into the Indian Coast Guard.",
    icon: "🚢",
    color: "from-teal-500 to-cyan-700",
    frequency: "Twice a year",
    papers: [
      { title: "Coast Guard Navik GD Section I Mock", subject: "Section I", durationMinutes: 45, marksPerQuestion: 1, negativeMarks: 0.25, subjects: ["Mathematics", "Science", "English", "Reasoning", "General Knowledge"], count: 45 },
    ],
  },
  {
    slug: "territorial-army",
    name: "Territorial Army",
    fullName: "Territorial Army Officer Examination",
    conductedBy: "Indian Army (TA Directorate)",
    force: "Army",
    eligibility: "Graduate, gainfully employed, age 18–42 years",
    pattern: "Paper I: Reasoning & Elementary Maths (100 marks). Paper II: GK & English (100 marks). 2 hrs each. Then PIB & SSB.",
    description: "Part-time commission for citizens who wish to serve the nation while continuing civilian careers.",
    icon: "🏅",
    color: "from-yellow-500 to-amber-700",
    frequency: "Once a year",
    papers: [
      { title: "TA Paper I Mock (Reasoning & Maths)", subject: "Paper I", durationMinutes: 120, marksPerQuestion: 1, negativeMarks: 0.33, subjects: ["Reasoning", "Mathematics"], count: 40 },
      { title: "TA Paper II Mock (GK & English)", subject: "Paper II", durationMinutes: 120, marksPerQuestion: 1, negativeMarks: 0.33, subjects: ["General Knowledge", "English", "Defence"], count: 40 },
    ],
  },
  {
    slug: "mns",
    name: "MNS (B.Sc Nursing)",
    fullName: "Military Nursing Service B.Sc Nursing Entrance",
    conductedBy: "Indian Army (via NEET score)",
    force: "Army",
    eligibility: "Female, 12th with PCB & English (50%), age 17–25 years",
    pattern: "Shortlisting on NEET score, then Test of General Intelligence & English (ToGIE), Psychological test, Interview & Medical.",
    description: "Commission as a Nursing Officer in the Armed Forces Medical Services.",
    icon: "🩺",
    color: "from-pink-500 to-fuchsia-700",
    frequency: "Once a year",
    papers: [
      { title: "MNS ToGIE Mock (Intelligence & English)", subject: "ToGIE", durationMinutes: 45, marksPerQuestion: 1, negativeMarks: 0, subjects: ["Reasoning", "English", "Science"], count: 40 },
    ],
  },
  {
    slug: "ssb",
    name: "SSB Interview",
    fullName: "Services Selection Board – 5 Day Process",
    conductedBy: "Indian Armed Forces",
    force: "Tri-Service",
    eligibility: "Candidates qualifying NDA/CDS/AFCAT/TA/Tech entries",
    pattern: "Day 1: OIR & PPDT. Day 2: Psychology (TAT, WAT, SRT, SD). Day 3–4: GTO tasks. Day 5: Conference. Personal Interview during days 2–4.",
    description: "The final personality & intelligence assessment for officer selection. Practice OIR tests here.",
    icon: "🧠",
    color: "from-violet-500 to-purple-800",
    frequency: "Ongoing (after written exam)",
    papers: [
      { title: "SSB OIR Test Set 1", subject: "Officer Intelligence Rating", durationMinutes: 30, marksPerQuestion: 1, negativeMarks: 0, subjects: ["Reasoning"], count: 40 },
      { title: "SSB OIR Test Set 2", subject: "Officer Intelligence Rating", durationMinutes: 30, marksPerQuestion: 1, negativeMarks: 0, subjects: ["Reasoning", "Mathematics"], count: 40 },
    ],
  },
];
